spring:
  application:
    name: board-service

server:
  port: 8763

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka/